// src/pages/games/typing/typingLevels.js

export const GAME_LEVELS = [
  {
    id: 'easy',
    title: 'Nível 1: Palavras Simples',
    description: 'Palavras curtas e essenciais do dia a dia.',
    phrases: [
      { text: "Oi", hint: "Saudação curta" },
      { text: "Sim", hint: "Afirmação" },
      { text: "Não", hint: "Negação" },
      { text: "Sol", hint: "Estrela do dia" },
      { text: "Lua", hint: "Estrela da noite" },
      { text: "Mar", hint: "Água salgada" },
      { text: "Céu", hint: "Acima de nós" },
      { text: "Pão", hint: "Alimento comum" },
      { text: "Uva", hint: "Fruta roxa ou verde" },
      { text: "Ovo", hint: "Vem da galinha" },
      { text: "Pé", hint: "Parte do corpo" },
      { text: "Mão", hint: "Tem cinco dedos" },
      { text: "Luz", hint: "Clareia o ambiente" },
      { text: "Cor", hint: "Azul, verde, vermelho" },
      { text: "Flor", hint: "Tem no jardim" },
      { text: "Casa", hint: "Onde moramos" },
      { text: "Gato", hint: "Animal de estimação" },
      { text: "Cão", hint: "Amigo fiel" },
      { text: "Ave", hint: "Animal que voa" },
      { text: "Boi", hint: "Animal da fazenda" },
      { text: "Vaca", hint: "Dá leite" },
      { text: "Bola", hint: "Usada no futebol" },
      { text: "Dado", hint: "Peça de jogo" },
      { text: "Faca", hint: "Corta alimentos" },
      { text: "Mala", hint: "Usada em viagens" },
      { text: "Sapo", hint: "Pula na lagoa" },
      { text: "Rato", hint: "Gosta de queijo" },
      { text: "Pato", hint: "Nada no lago" },
      { text: "Vela", hint: "Ilumina no escuro" },
      { text: "Anel", hint: "Joia de dedo" },
      { text: "Mel", hint: "Doce de abelha" },
      { text: "Sal", hint: "Tempero branco" },
      { text: "Som", hint: "O que ouvimos" },
      { text: "Pai", hint: "Familiar" },
      { text: "Mãe", hint: "Familiar" },
      { text: "Tia", hint: "Familiar" },
      { text: "Avô", hint: "Familiar" },
      { text: "Avó", hint: "Familiar" },
      { text: "Bebê", hint: "Criança pequena" },
      { text: "Vovó", hint: "Apelido carinhoso" },
      { text: "Vovô", hint: "Apelido carinhoso" },
      { text: "Rua", hint: "Onde passam carros" },
      { text: "Dia", hint: "Oposto de noite" },
      { text: "Ano", hint: "Tem 12 meses" },
      { text: "Mês", hint: "Parte do ano" },
      { text: "Fim", hint: "Término" },
      { text: "Olá", hint: "Cumprimento" },
      { text: "Alô", hint: "Ao telefone" },
      { text: "Bem", hint: "Estado positivo" },
      { text: "Mal", hint: "Estado negativo" },
      { text: "Bom", hint: "Qualidade positiva" },
      { text: "Mau", hint: "Contrário de bom" },
      { text: "Um", hint: "Número 1" },
      { text: "Dois", hint: "Número 2" },
      { text: "Três", hint: "Número 3" },
      { text: "Dez", hint: "Número 10" },
      { text: "Mil", hint: "Número 1000" },
      { text: "Eu", hint: "Pronome pessoal" },
      { text: "Tu", hint: "Pronome pessoal" },
      { text: "Ele", hint: "Pronome pessoal" },
      { text: "Nós", hint: "Pronome pessoal" },
      { text: "Ir", hint: "Verbo mover-se" },
      { text: "Vir", hint: "Verbo chegar" },
      { text: "Ser", hint: "Verbo existir" },
      { text: "Ter", hint: "Verbo possuir" },
      { text: "Ler", hint: "Verbo (leitura)" },
      { text: "Ver", hint: "Verbo (visão)" },
      { text: "Dar", hint: "Verbo oferecer" },
      { text: "Rir", hint: "Verbo (alegria)" },
      { text: "Dor", hint: "Sensação ruim" },
      { text: "Fé", hint: "Crença" },
      { text: "Paz", hint: "Tranquilidade" },
      { text: "Rei", hint: "Monarca" },
      { text: "Lã", hint: "Pelo de ovelha" },
      { text: "Pó", hint: "Poeira" },
      { text: "Nó", hint: "Amarração" },
      { text: "Fio", hint: "Linha" },
      { text: "Rio", hint: "Curso de água" },
      { text: "Lago", hint: "Água parada" },
      { text: "Mato", hint: "Vegetação" },
      { text: "Vila", hint: "Povoado" },
      { text: "Bule", hint: "Para café" },
      { text: "Café", hint: "Bebida escura" },
      { text: "Leite", hint: "Bebida branca" },
      { text: "Suco", hint: "Bebida de fruta" },
      { text: "Água", hint: "Bebida vital" },
      { text: "Copo", hint: "Para beber" },
      { text: "Fogo", hint: "Quente" },
      { text: "Gelo", hint: "Frio" },
      { text: "Frio", hint: "Temperatura baixa" },
      { text: "Calor", hint: "Temperatura alta" },
      { text: "Alto", hint: "Estatura grande" },
      { text: "Baixo", hint: "Estatura pequena" },
      { text: "Novo", hint: "Recente" },
      { text: "Velho", hint: "Antigo" },
      { text: "Belo", hint: "Bonito" },
      { text: "Feio", hint: "Não bonito" },
      { text: "Vida", hint: "Existência" },
      { text: "Amor", hint: "Afeto" },
      { text: "Ouro", hint: "Metal precioso" }
    ]
  },
  {
    id: 'medium',
    title: 'Nível 2: Frases do Dia a Dia',
    description: 'Mensagens comuns de WhatsApp e conversas.',
    phrases: [
      { text: "Bom dia!", hint: "Ao acordar" },
      { text: "Boa tarde.", hint: "Depois do almoço" },
      { text: "Boa noite.", hint: "Ao anoitecer" },
      { text: "Tudo bem?", hint: "Pergunta comum" },
      { text: "Como vai?", hint: "Pergunta comum" },
      { text: "Até logo.", hint: "Despedida" },
      { text: "Até amanhã.", hint: "Despedida" },
      { text: "Tchau tchau.", hint: "Despedida informal" },
      { text: "Muito obrigado.", hint: "Agradecimento" },
      { text: "De nada.", hint: "Resposta ao obrigado" },
      { text: "Por favor.", hint: "Pedindo com educação" },
      { text: "Com licença.", hint: "Pedindo passagem" },
      { text: "Desculpe.", hint: "Pedindo perdão" },
      { text: "Meus parabéns!", hint: "Felicitações" },
      { text: "Feliz aniversário!", hint: "Festa anual" },
      { text: "Boas festas.", hint: "Fim de ano" },
      { text: "Feliz Natal.", hint: "Em dezembro" },
      { text: "Feliz Ano Novo.", hint: "Em janeiro" },
      { text: "Bom fim de semana.", hint: "Sexta-feira" },
      { text: "Bom descanso.", hint: "Para quem vai relaxar" },
      { text: "Bom trabalho.", hint: "Para quem vai trabalhar" },
      { text: "Bom apetite.", hint: "Antes de comer" },
      { text: "Estou com fome.", hint: "Vontade de comer" },
      { text: "Estou com sede.", hint: "Vontade de beber" },
      { text: "Vamos almoçar?", hint: "Convite para comer" },
      { text: "O que tem para comer?", hint: "Pergunta sobre comida" },
      { text: "A conta, por favor.", hint: "No restaurante" },
      { text: "Aceita cartão?", hint: "Forma de pagamento" },
      { text: "Quanto custa?", hint: "Pergunta de preço" },
      { text: "Que horas são?", hint: "Pergunta de horário" },
      { text: "Onde é o banheiro?", hint: "Pergunta de local" },
      { text: "Preciso de ajuda.", hint: "Pedindo auxílio" },
      { text: "Pode me ajudar?", hint: "Pedindo auxílio" },
      { text: "Não entendi.", hint: "Dúvida" },
      { text: "Fale mais devagar.", hint: "Para entender melhor" },
      { text: "Repita, por favor.", hint: "Para ouvir de novo" },
      { text: "Qual é a senha?", hint: "Wi-Fi ou acesso" },
      { text: "Estou chegando.", hint: "Aviso de chegada" },
      { text: "Já estou indo.", hint: "Aviso de saída" },
      { text: "Estou atrasado.", hint: "Fora do horário" },
      { text: "Me liga depois.", hint: "Pedido de contato" },
      { text: "Vou te ligar.", hint: "Promessa de contato" },
      { text: "Mande mensagem.", hint: "Pedido de texto" },
      { text: "Olha o WhatsApp.", hint: "Aviso de notificação" },
      { text: "Gostei da foto.", hint: "Elogio em rede social" },
      { text: "Você está linda.", hint: "Elogio" },
      { text: "Você está lindo.", hint: "Elogio" },
      { text: "Adorei o presente.", hint: "Agradecimento" },
      { text: "Foi muito bom.", hint: "Elogio de evento" },
      { text: "Não gostei.", hint: "Opinião negativa" },
      { text: "Eu concordo.", hint: "Opinião igual" },
      { text: "Eu discordo.", hint: "Opinião diferente" },
      { text: "Talvez sim.", hint: "Dúvida" },
      { text: "Talvez não.", hint: "Dúvida" },
      { text: "Claro que sim.", hint: "Certeza" },
      { text: "Com certeza.", hint: "Confirmação" },
      { text: "Nunca mais.", hint: "Negação forte" },
      { text: "Sempre juntos.", hint: "Afeto" },
      { text: "Te amo muito.", hint: "Declaração de amor" },
      { text: "Estou com saudades.", hint: "Falta de alguém" },
      { text: "Um grande beijo.", hint: "Carinho" },
      { text: "Um forte abraço.", hint: "Carinho" },
      { text: "Fica com Deus.", hint: "Bênção" },
      { text: "Vá com Deus.", hint: "Despedida religiosa" },
      { text: "Deus te abençoe.", hint: "Bênção" },
      { text: "Hoje vai chover.", hint: "Previsão do tempo" },
      { text: "Hoje está sol.", hint: "Clima bom" },
      { text: "Está muito calor.", hint: "Clima quente" },
      { text: "Está muito frio.", hint: "Clima gelado" },
      { text: "Vamos sair?", hint: "Convite" },
      { text: "Vamos ao cinema?", hint: "Convite" },
      { text: "Vamos ao parque?", hint: "Convite" },
      { text: "Quer carona?", hint: "Oferecendo transporte" },
      { text: "Onde você mora?", hint: "Pergunta pessoal" },
      { text: "Qual seu nome?", hint: "Pergunta pessoal" },
      { text: "Prazer em conhecer.", hint: "Apresentação" },
      { text: "O prazer é meu.", hint: "Resposta educada" },
      { text: "Tenha calma.", hint: "Conselho" },
      { text: "Não se preocupe.", hint: "Consolo" },
      { text: "Vai dar tudo certo.", hint: "Otimismo" },
      { text: "Boa sorte!", hint: "Desejo de êxito" },
      { text: "Boa viagem.", hint: "Para quem vai viajar" },
      { text: "Cuidado na estrada.", hint: "Aviso de segurança" },
      { text: "Feche a porta.", hint: "Ordem simples" },
      { text: "Apague a luz.", hint: "Economia" },
      { text: "Abra a janela.", hint: "Ventilação" },
      { text: "Lave as mãos.", hint: "Higiene" },
      { text: "Escove os dentes.", hint: "Higiene" },
      { text: "Tome o remédio.", hint: "Saúde" },
      { text: "Beba água.", hint: "Hidratação" },
      { text: "Vou dormir.", hint: "Sono" },
      { text: "Acorde cedo.", hint: "Horário" },
      { text: "Estou cansado.", hint: "Fadiga" },
      { text: "Estou feliz.", hint: "Alegria" },
      { text: "Estou triste.", hint: "Tristeza" },
      { text: "Que legal!", hint: "Entusiasmo" },
      { text: "Que pena.", hint: "Lamento" },
      { text: "Nossa!", hint: "Surpresa" }
    ]
  },
  {
    id: 'hard',
    title: 'Nível 3: Frases Completas',
    description: 'Ditados, provérbios e frases mais longas.',
    phrases: [
      { text: "A pressa é a inimiga da perfeição.", hint: "Ditado popular" },
      { text: "Águas passadas não movem moinhos.", hint: "Não adianta lamentar" },
      { text: "Quem não tem cão caça com gato.", hint: "Improviso" },
      { text: "De grão em grão a galinha enche o papo.", hint: "Paciência" },
      { text: "Mais vale um pássaro na mão do que dois voando.", hint: "Segurança" },
      { text: "Cavalo dado não se olha os dentes.", hint: "Gratidão" },
      { text: "Em casa de ferreiro, o espeto é de pau.", hint: "Ironia" },
      { text: "Quem ri por último ri melhor.", hint: "Vitória final" },
      { text: "Filho de peixe, peixinho é.", hint: "Semelhança familiar" },
      { text: "Onde há fumaça, há fogo.", hint: "Desconfiança" },
      { text: "Mentira tem perna curta.", hint: "Verdade aparece" },
      { text: "Quem avisa amigo é.", hint: "Conselho" },
      { text: "Cada macaco no seu galho.", hint: "Cada um no seu lugar" },
      { text: "Devagar se vai ao longe.", hint: "Persistência" },
      { text: "Quem espera sempre alcança.", hint: "Fé" },
      { text: "Antes tarde do que nunca.", hint: "Atraso aceitável" },
      { text: "O barato sai caro.", hint: "Qualidade importa" },
      { text: "Nem tudo que reluz é ouro.", hint: "Aparências enganam" },
      { text: "Santo de casa não faz milagre.", hint: "Valorizar os de fora" },
      { text: "Quem canta seus males espanta.", hint: "Alegria" },
      { text: "Deus ajuda quem cedo madruga.", hint: "Esforço" },
      { text: "Roupa suja se lava em casa.", hint: "Privacidade" },
      { text: "Cão que ladra não morde.", hint: "Ameaça vazia" },
      { text: "A união faz a força.", hint: "Trabalho em equipe" },
      { text: "Quem tem boca vai a Roma.", hint: "Comunicação" },
      { text: "Mente vazia, oficina do diabo.", hint: "Ocupação" },
      { text: "Não deixe para amanhã o que pode fazer hoje.", hint: "Procrastinação" },
      { text: "O seguro morreu de velho.", hint: "Prevenção" },
      { text: "Saco vazio não para em pé.", hint: "Alimentação" },
      { text: "Quem ama o feio, bonito lhe parece.", hint: "O amor é cego" },
      { text: "Gosto não se discute.", hint: "Opinião pessoal" },
      { text: "O que os olhos não veem, o coração não sente.", hint: "Ignorância é bênção" },
      { text: "Errar é humano.", hint: "Compreensão" },
      { text: "A esperança é a última que morre.", hint: "Otimismo" },
      { text: "Quem semeia vento, colhe tempestade.", hint: "Consequências" },
      { text: "Vaso ruim não quebra.", hint: "Resiliência irônica" },
      { text: "Tapar o sol com a peneira.", hint: "Esforço inútil" },
      { text: "Caiu na rede é peixe.", hint: "Aproveitar oportunidade" },
      { text: "Quem não arrisca não petisca.", hint: "Coragem" },
      { text: "Papagaio que acompanha joão-de-barro vira ajudante de pedreiro.", hint: "Más companhias" },
      { text: "Diga-me com quem andas e te direi quem és.", hint: "Reputação" },
      { text: "Em terra de cego, quem tem um olho é rei.", hint: "Vantagem relativa" },
      { text: "Um dia da caça, outro do caçador.", hint: "Alternância" },
      { text: "Não conte com os ovos dentro da galinha.", hint: "Antecipação" },
      { text: "O sol nasce para todos.", hint: "Igualdade" },
      { text: "Há males que vêm para o bem.", hint: "Consolo" },
      { text: "Querer é poder.", hint: "Força de vontade" },
      { text: "O saber não ocupa lugar.", hint: "Conhecimento" },
      { text: "A prática leva à perfeição.", hint: "Treino" },
      { text: "Quem fala demais dá bom dia a cavalo.", hint: "Falar muito" },
      { text: "Boca fechada não entra mosca.", hint: "Silêncio" },
      { text: "É melhor prevenir do que remediar.", hint: "Saúde" },
      { text: "Para bom entendedor, meia palavra basta.", hint: "Inteligência" },
      { text: "O mundo dá voltas.", hint: "Mudança" },
      { text: "Quem desdenha quer comprar.", hint: "Interesse disfarçado" },
      { text: "Cada um sabe onde o sapato aperta.", hint: "Problema pessoal" },
      { text: "Não julgue o livro pela capa.", hint: "Preconceito" },
      { text: "A mentira tem perna curta.", hint: "Verdade" },
      { text: "Água mole em pedra dura tanto bate até que fura.", hint: "Insistência" },
      { text: "Quem tudo quer nada tem.", hint: "Ganância" },
      { text: "Por fora bela viola, por dentro pão bolorento.", hint: "Falsidade" },
      { text: "Ladrão que rouba ladrão tem cem anos de perdão.", hint: "Justiça torta" },
      { text: "Quem casa quer casa.", hint: "Independência" },
      { text: "A ocasião faz o ladrão.", hint: "Oportunidade" },
      { text: "Onde o rei perdeu as botas.", hint: "Lugar longe" },
      { text: "Matar dois coelhos com uma cajadada só.", hint: "Eficiência" },
      { text: "Trocar seis por meia dúzia.", hint: "Mesma coisa" },
      { text: "Procurar chifre em cabeça de cavalo.", hint: "Problema inexistente" },
      { text: "Colocar a carroça na frente dos bois.", hint: "Pressa errada" },
      { text: "Chorar sobre o leite derramado.", hint: "Arrependimento tardio" },
      { text: "Quem conta um conto aumenta um ponto.", hint: "Fofoca" },
      { text: "A voz do povo é a voz de Deus.", hint: "Democracia" },
      { text: "Quem cala consente.", hint: "Acordo tácito" },
      { text: "Gato escaldado tem medo de água fria.", hint: "Trauma" },
      { text: "Pimenta nos olhos dos outros é refresco.", hint: "Egoísmo" },
      { text: "Uma andorinha sozinha não faz verão.", hint: "Solidão" },
      { text: "Quem planta colhe.", hint: "Justiça" },
      { text: "O futuro a Deus pertence.", hint: "Destino" },
      { text: "Tempo é dinheiro.", hint: "Valor do tempo" },
      { text: "O amor move montanhas.", hint: "Poder do amor" },
      { text: "Gentileza gera gentileza.", hint: "Educação" },
      { text: "A justiça tarda mas não falha.", hint: "Lei" },
      { text: "Quem tem pressa come cru.", hint: "Impaciência" },
      { text: "Os últimos serão os primeiros.", hint: "Bíblico" },
      { text: "Fazer o bem sem olhar a quem.", hint: "Caridade" },
      { text: "O hábito faz o monge.", hint: "Costume" },
      { text: "Quem procura acha.", hint: "Busca" },
      { text: "A curiosidade matou o gato.", hint: "Perigo" },
      { text: "Tamanho não é documento.", hint: "Qualidade" },
      { text: "Recordar é viver.", hint: "Memória" },
      { text: "A necessidade é a mãe da invenção.", hint: "Criatividade" },
      { text: "Depois da tempestade vem a bonança.", hint: "Esperança" },
      { text: "Quem não chora não mama.", hint: "Reivindicação" },
      { text: "Amigos, amigos, negócios à parte.", hint: "Profissionalismo" },
      { text: "Viver é aprender.", hint: "Sabedoria" },
      { text: "O saber é poder.", hint: "Conhecimento" },
      { text: "A vida é bela.", hint: "Otimismo" },
      { text: "Sorrir é o melhor remédio.", hint: "Alegria" },
      { text: "A fé remove montanhas.", hint: "Crença" },
      { text: "Pense antes de falar.", hint: "Prudência" }
    ]
  }
];